pipeline{
    agent none
    stages{
        stage('Build'){
			agent any
			optons {
                skipDefaultCheckout()
            }   
		
            steps{
                echo "Hello World ""
            }
        }		
    }
}
